### ISSUE TITLE
`release.json` is malformed

### ISSUE THREAD

**Issue by layday** [tflo/PetWalker#3]
`releases` must contain a `metadata` property with two required properties, `flavor` and `interface`. `flavor` must be one of `"mainline"`, `"classic"` or `"wrath"`, and `interface` is the TOC version as a number.

**Comment by tflo** [comment]
Thanks. Hopefully fixed now.

**Comment by tflo** [comment]
The addon is still not visible in instawow's search. 

The release.json is:
```json
{"releases":[{"name":"PetWalker","version":"1.1.1","filename":"PetWalker-1.1.1.zip","nolib":false,"metadata":[{"flavor":"mainline","interface":90207}]}]}
```
Looks fine to me (AFAICT). Are there any other requirements that are not met?

**Comment by layday** [comment]
It's just not been picked up by https://github.com/layday/github-wow-addon-catalogue yet - I haven't run it in 2 weeks :)

**Comment by layday** [comment]
Your add-ons have been added to the catalogue now with the exception of https://github.com/tflo/AutoConfirmEquip which is still missing the metadata prop.

**Comment by tflo** [comment]
> I haven't run it in 2 weeks :)

Ah, OK. I thought waiting 10 days was enough ;)

> Your add-ons have been added to the catalogue now

Thank you!

> with the exception of https://github.com/tflo/AutoConfirmEquip which is still missing the metadata prop

You must have picked the old release (1.0.0). The current one (1.0.1) has been fixed with the other addons 11 days ago. (But I have now also updated the json of the old one.)

Thanks

– Tom

**Comment by layday** [comment]
I think AutoConfirmEquip's `release.json` was cached. I'll run it again later, cheers.
